<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTtTvyUy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTtTvyUy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTtTvyUy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTtTvyUy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTtTvyUy\App_KernelDevDebugContainer([
    'container.build_hash' => 'TtTvyUy',
    'container.build_id' => '26243b00',
    'container.build_time' => 1638887943,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTtTvyUy');
